spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foro?useSSL=false&serverTimezone=UTC
    username: forohub_app
    password: uZ5!kH7m1$w4Q8rT2@b9
  jpa:
    hibernate:
      ddl-auto: validate   # usaremos Flyway para crear tablas
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
